name: Daily Pick My Postcode Check

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Install Python dependencies
        run: pip install selenium

      - name: Run postcode checker
        env:
          EMAIL: ${{ secrets.EMAIL }}
          POSTCODE: ${{ secrets.POSTCODE }}
          APP_PASS: ${{ secrets.APP_PASS }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
        run: |
          python check_draws.py
